"""FastAPI server implementing Grand Challenge's ``invoke`` API for ISLES 2026.

This file is verbatim from the official template at
https://github.com/ezequieldlrosa/isles26-docker-template/blob/main/app.py

Do NOT edit this file - edit ``inference.py`` instead. Grand Challenge boots
this server, polls ``GET /health`` until 200, then calls ``POST /invoke``
once per case (fresh ``/input`` and ``/output`` on each call).
"""

from contextlib import asynccontextmanager

import inference
import uvicorn
from fastapi import FastAPI, Response, status
from uvicorn.config import LOGGING_CONFIG

MODEL = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Load the SADL ensemble once at startup; release on shutdown."""
    global MODEL
    MODEL = inference.init_model()
    yield
    MODEL = None


app = FastAPI(lifespan=lifespan)


@app.get("/health")
async def health():
    """200 when the ensemble is loaded, 503 while still loading. No redirects."""
    if MODEL is None:
        return Response(status_code=status.HTTP_503_SERVICE_UNAVAILABLE)
    return Response(status_code=status.HTTP_200_OK)


@app.post("/invoke")
async def invoke():
    """One case per call. Reads ``/input``, writes ``/output``, returns 201."""
    inference.run(MODEL)
    return Response(status_code=status.HTTP_201_CREATED)


if __name__ == "__main__":
    log_config = LOGGING_CONFIG.copy()
    log_config["handlers"]["default"]["stream"] = "ext://sys.stdout"
    uvicorn.run(app, host="0.0.0.0", port=4743, log_config=log_config)
