name: nnunet_default
mode: nnunet_v2_default
gin: {enabled: false, p: 0.5, n_layers: 4, channels: 2}
mixstyle: {enabled: false, p: 0.5, alpha: 0.1}
bigaug: {enabled: false, p: 0.3}
carvemix: {enabled: false, p: 0.3, margin_voxels: 6, lesion_bank_dir: null}
